steering_smoother_queue_length: 10
Kp: .2
Ki: .2
Kd: .1

# Some slow speeds we just can't do because of oscillating stiction
# (perhaps a fancier model-based speed controller could overcome this).
min_nonzero_speed: 0.2

# How much to smooth speed measurements before passing them on to the controller.
# Probably not a good idea; it just deprives the controller of
speed_measurment_smoothing_window: 1

# This stops the car from braking if the control output goes to zero, and thereby ]
# triggering the zero-throttle step (see min_abs_throttle below).
min_abs_pseudovelocity: 0.05

# If this is smaller, the controls are touchier, and so e.g. kp should be smaller.
pseudovelocity_rate_scaling: 1

# This offset is the value that throttle jumps to after the control signal becomes nonzero, but near-zero.
# This overrides the controller at "low" speed, giving a flat throttle.

# Traxxas mode 3:
#min_abs_throttle: .1

# Traxxas mode 1:
min_abs_throttle: .08

cmd_angle_instead_rotvel: False

zero_command_timeout: 2.0
