steering_smoother_queue_length: 20
Kp: .2
Ki: .3
Kd: .05

# Some slow speeds we just can't do because of oscillating stiction
# (perhaps a fancier model-based speed controller could overcome this).
min_nonzero_speed: 0.15

# How much to smooth speed measurements before passing them on to the controller.
# Probably not a good idea; it just deprives the controller of
speed_measurment_smoothing_window: 1

# This stops the car from braking if the control output goes to zero, and thereby ]
# triggering the zero-throttle step (see min_abs_throttle below).
min_abs_pseudovelocity: 0.05

# If this is smaller, the controls are touchier, and so e.g. kp should be smaller.
pseudovelocity_rate_scaling: 1

# This offset is the value that throttle jumps to after the control signal becomes nonzero, but near-zero.
# However, this is dangerous to make too small, as it overrides the controller at "low" speed, giving a flat throttle.
min_abs_throttle: .05