raytrace_range: 3.0

# 11 in wide
#   .279 m
# 23 in long
#   .584 m
footprint: [[ 0.4695,  0.140], [-0.1145,  0.140], [-0.1145, -0.140], [ 0.4695, -0.140]]
footprint_padding: 0.0
#robot_radius: ir_of_robot

controller_patience: 2.0

NavfnROS:
  allow_unknown: true

recovery_behaviors: [
    # {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    # {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
]

# conservative_clear: 
#     reset_distance: 6.0
# aggressive_clear:
#     reset_distance: 6.0

origin_x: -8
origin_y: -8

obstacle_range: 6.0

track_unknown_space: false