# # Large rubber wheels
# meters_per_wheel_diameter: 0.105

# # Small rubber wheels
# meters_per_wheel_diameter: 0.0508

# Medium diameter hard plastic wheels
meters_per_wheel_diameter: 0.087

reversed: true