global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.5
  publish_frequency: 0.5
  static_map: false
  transform_tolerance: 5.0

  height: 24.
  width: 24.

  plugins:
   - {name: static_layer,            type: "costmap_2d::StaticLayer"}
   # - {name: laserscan_layer,          type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  inflation_layer:
    inflation_radius: 0.25

  laserscan_layer:
    observation_sources: laser_scan_sensor

    laser_scan_sensor: 
      sensor_frame: d400_depth_frame
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      # Since the virtual laser sensor is a little tilted, we need a significant min_obstacle_height
      # to include both below-plane and above-plane (default) detections.
      min_obstacle_height: -1.0
      max_obstacle_height: 3.0
      #inf_is_valid: true



