local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.025
  origin_x: -2.0
  origin_y: -2.0

  obstacle_layer:
    observation_sources: laser_scan_sensor

    laser_scan_sensor: {
      sensor_frame: camera_depth_frame,
      data_type: LaserScan,
      topic: /scan,
      marking: true,
      clearing: true
    }

    # assuming receiving a cloud from rtabmap_ros/obstacles_detection node
    # point_cloud_sensor: {
    #   sensor_frame: camera_link,
    #   data_type: PointCloud2, 
    #   topic: openni_points, 
    #   expected_update_rate: 1, 
    #   marking: true, 
    #   clearing: true,
    #   min_obstacle_height: -99999.0,
    #   max_obstacle_height: 99999.0}
